### ISSUE TITLE
有个问题想和您讨论下

### ISSUE THREAD

**Issue by ghostviper** [waltyou/faiss-web-service#1]
不同图片会有不同维度的sift特征，看了您关于搜索时候的计算公式是利用匹配求和的方式，我尝试了您的方式出来的结果不太好，不知道您有没有试过sift特征提取然后聚类标注，在利用tfidf来进行相似度对比的方式；另外可以用deep的方式对图片进行提取特征在进行PCA降维对比的方式。

**Comment by waltyou** [comment]
1）使用sift提取局部特征，然后聚类合成全局特征，这个是个经典的方式，实际中应用的也比较多。但是聚类方式通常有三种比较常见的方式：词袋模型（BoW, Bag of Words)、 局部特征聚合描述符(VLAD, Vector of Locally Aggregated Descriptors)以及Fisher向量(FV, Fisher Vector)。tf-idf 是否合适，我没有了解过。不过，我当时有实现了 BoW 流程的代码，你可以看看[这里](https://github.com/waltyou/faiss-web-service/blob/master/src/train_index/train_index_bow.py)。
2）deep learning 方式 和 PCA 降维，我暂时没有试过。

**Comment by ghostviper** [comment]
好呢 谢谢 分享
