### ISSUE TITLE
在index的时候报错，请问是图片的问题吗？

### ISSUE THREAD

**Issue by wongdu** [waltyou/faiss-web-service#3]
RuntimeError: Error in void faiss::Clustering::train_encoded(faiss::Clustering::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at Clustering.cpp:273: Error: 'nx >= k' failed: Number of training points (796) should be at least as large as number of clusters (1024)

**Comment by wongdu** [comment]
直接执行"python train_index.py"，然后报了上面的错误，不知道是否是图片的问题？

**Comment by waltyou** [comment]
错误的根本原因是你提供的图片太少，所以输入给Faiss的特征向量就少。就像错误日志里说的："Number of training points (796) should be at least as large as number of clusters (1024)"，你只提供了 796个向量，我代码默认的index类型是 [IDMap,IMI2x10,Flat](https://github.com/waltyou/faiss-web-service/blob/master/src/config.py#L43). 这个 ”…,IMI2x10,…” 默认是要输入1百万-1千万个向量才是合适的。这里详细解释 [here](https://waltyou.github.io/Faiss-Indexs/#%E5%A6%82%E6%9E%9C%E5%90%91%E9%87%8F%E6%95%B0%E9%87%8F%E4%BD%8D%E4%BA%8E1%E7%99%BE%E4%B8%87-1%E5%8D%83%E4%B8%87%E4%B9%8B%E9%97%B4imi2x10). 

所以你有两个选择。1、增加图片数量；2、改变index类型，看[这里](https://waltyou.github.io/Faiss-Indexs/#%E6%8C%91%E4%B8%80%E4%B8%AA%E5%90%88%E9%80%82%E7%9A%84-index)教你选择一个合适的index type。对于你这么少的向量数，其实可以使用 “IDMap,Flat”，就是我注释掉的[这一行](https://github.com/waltyou/faiss-web-service/blob/master/src/config.py#L42)

**Comment by wongdu** [comment]
嗯嗯，非常感谢哈，我先看看你写的文章
