### ISSUE TITLE
train_index.py中index_dict中也保存了sift_feature，是否有必要？

### ISSUE THREAD

**Issue by ZhangXinNan** [waltyou/faiss-web-service#5]
train_index.py中，index里保存了sift_feature，index_dict中也保存了sift_feature，是否重复保存了？都保存的话两个文件都会比较大。

**Comment by waltyou** [comment]
这个看你的需求了。index_dict中保存了sift_feature 后，下次就不需要重新计算每张图片的feature，直接读取就好。但是如果你觉得没必要，也可以不存。

**Comment by waltyou** [comment]
no response for a long time. close it by now.
